create table comment (id bigint generated by default as identity, post_id bigint, user_id bigint, reply varchar(255), primary key (id));
alter table if exists comment add constraint FKs1slvnkuemjsq2kj4h3vhx7i1 foreign key (post_id) references post;
alter table if exists comment add constraint FKjm63kayatnav3o7c890jldqji foreign key (user_id) references user_tbl;